// data.js
const products = [
  // --- NHÓM: ÁO NỮ ---
  { 
    id: 1, 
    name: "Áo khoác Blazer nữ Hàn Quốc", 
    slug: "ao-khoac-blazer-nu-han-quoc",
    category: "Áo khoác", 
    subCategory: "Áo Nữ", 
    price: 705000, 
    oldPrice: 850000, 
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800", 
    tag: "Bán chạy", 
    code: "BLZ-001",
    sizes: ["S", "M", "L"],
    description: "Thiết kế form suông hiện đại theo phong cách Hàn Quốc, chất liệu vải cao cấp không nhăn, bề mặt vải mịn màng, phù hợp cho cả môi trường công sở lẫn các buổi tiệc sang trọng."
  },
  { 
    id: 2, 
    name: "Áo Hoodie nỉ form rộng", 
    slug: "ao-hoodie-ni-form-rong",
    category: "Áo hoodie", 
    subCategory: "Áo Nữ", 
    price: 350000, 
    oldPrice: 450000, 
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800", 
    tag: "Mới", 
    code: "HDD-002",
    sizes: ["M", "L"],
    description: "Chất liệu nỉ ngoại dày dặn, mặt trong lót bông mềm mại giúp giữ ấm hiệu quả. Thiết kế mũ rộng và túi bụng tiện lợi, mang lại phong cách streetwear năng động."
  },
  { 
    id: 3, 
    name: "Áo len lưới croptop Vienne", 
    slug: "ao-len-luoi-croptop-vienne",
    category: "Áo len", 
    subCategory: "Áo Nữ", 
    price: 249000, 
    oldPrice: 368000, 
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800", 
    tag: "Sale", 
    code: "LEN-003",
    sizes: ["S", "M"],
    description: "Sợi len dệt lưới thưa phong cách, kiểu dáng croptop quyến rũ. Đây là lựa chọn hoàn hảo để phối cùng áo bra hoặc áo hai dây bên trong khi dạo phố."
  },
  { 
    id: 4, 
    name: "Áo sơ mi lụa công sở", 
    slug: "ao-so-mi-lua-cong-so",
    category: "Áo sơ mi", 
    subCategory: "Áo Nữ", 
    price: 250000, 
    oldPrice: 320000, 
    image: "https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800", 
    tag: "", 
    code: "SMI-004",
    sizes: ["S", "M", "L", "XL"],
    description: "Vải lụa satin mềm mịn, độ rủ tự nhiên giúp tôn dáng người mặc. Áo có độ bóng nhẹ sang trọng, không bám bụi và cực kỳ thoáng mát."
  },
  { 
    id: 5, 
    name: "Áo thun Cotton basic", 
    slug: "ao-thun-cotton-basic",
    category: "Áo thun", 
    subCategory: "Áo Nữ", 
    price: 150000, 
    oldPrice: 180000, 
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800", 
    tag: "Mới", 
    code: "TSH-005",
    sizes: ["S", "M", "L"],
    description: "Áo thun 100% cotton co giãn 4 chiều, chất vải xử lý chống xù lông, thấm hút mồ hôi cực tốt giúp bạn thoải mái suốt ngày dài."
  },

  // --- NHÓM: QUẦN NỮ ---
  { 
    id: 6, 
    name: "Quần Jean Baggy nữ", 
    slug: "quan-jean-baggy-nu",
    category: "Quần jeans", 
    subCategory: "Quần Nữ", 
    price: 390000, 
    oldPrice: 500000, 
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800", 
    tag: "", 
    code: "JEA-006",
    sizes: ["S", "M", "L"],
    description: "Thiết kế lưng cao giúp đôi chân thon dài, chất jean denim dày dặn đứng form, che khuyết điểm vùng hông và đùi cực tốt."
  },
  { 
    id: 7, 
    name: "Quần Short thun năng động", 
    slug: "quan-short-thun-nu",
    category: "Quần short", 
    subCategory: "Quần Nữ", 
    price: 120000, 
    oldPrice: 180000, 
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800", 
    tag: "Sale", 
    code: "SHO-007",
    sizes: ["S", "M"],
    description: "Chất liệu thun cotton mềm mại, cạp chun co giãn thoải mái. Thích hợp cho các hoạt động thể thao nhẹ, tập gym hoặc mặc ở nhà."
  },
  { 
    id: 8, 
    name: "Quần dài ống suông", 
    slug: "quan-dai-ong-suong",
    category: "Quần dài", 
    subCategory: "Quần Nữ", 
    price: 280000, 
    oldPrice: 350000, 
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800", 
    tag: "Mới", 
    code: "TRO-008",
    sizes: ["M", "L", "XL"],
    description: "Quần ống suông thanh lịch với chất vải tuyết mưa cao cấp, không nhăn, tạo cảm giác sang trọng và chuyên nghiệp."
  },

  // --- NHÓM: ÁO NAM ---
  { 
    id: 9, 
    name: "Áo sơ mi Oxford nam", 
    slug: "ao-so-mi-oxford-nam",
    category: "Áo sơ mi", 
    subCategory: "Áo Nam", 
    price: 380000, 
    oldPrice: 450000, 
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800", 
    tag: "Mới", 
    code: "MSM-009",
    sizes: ["M", "L", "XL", "XXL"],
    description: "Vải Oxford có bề mặt hơi nhám đặc trưng, độ bền cao và ít nhăn. Form áo Regular Fit mang lại vẻ ngoài trẻ trung nhưng vẫn rất lịch sự."
  },
  { 
    id: 10, 
    name: "Áo thun Polo phối cổ", 
    slug: "ao-thun-polo-phoi-co",
    category: "Áo polo", 
    subCategory: "Áo Nam", 
    price: 280000, 
    oldPrice: 350000, 
    image: "https://images.unsplash.com/photo-1624371414361-e6e0ed58d38c?w=800", 
    tag: "Bán chạy", 
    code: "POL-010",
    sizes: ["M", "L", "XL"],
    description: "Vải thun cá sấu co giãn mạnh, cổ áo dệt kim chắc chắn không bị nhão. Màu sắc trung tính dễ dàng kết hợp với nhiều loại quần khác nhau."
  },
  { 
    id: 11, 
    name: "Áo Hoodie Streetwear", 
    slug: "ao-hoodie-streetwear-nam",
    category: "Áo hoodie", 
    subCategory: "Áo Nam", 
    price: 450000, 
    oldPrice: 550000, 
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800", 
    tag: "", 
    code: "MHD-011",
    sizes: ["L", "XL", "XXL"],
    description: "Họa tiết in nhiệt bền bỉ, không bong tróc. Form áo Oversize cực rộng rãi theo xu hướng thời trang đường phố hiện đại."
  },
  { 
    id: 12, 
    name: "Áo thun trơn nam", 
    slug: "ao-thun-tron-nam",
    category: "Áo thun", 
    subCategory: "Áo Nam", 
    price: 190000, 
    oldPrice: 250000, 
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800", 
    tag: "Sale", 
    code: "MTS-012",
    sizes: ["M", "L", "XL"],
    description: "Basic T-shirt với chất cotton lụa cực mát. Phù hợp để làm áo lót bên trong hoặc mặc trơn để khoe hình thể khỏe khoắn."
  },

  // --- NHÓM: QUẦN NAM ---
  { 
    id: 13, 
    name: "Quần Jean Slim-fit Nam", 
    slug: "quan-jean-slim-fit-nam",
    category: "Quần jeans", 
    subCategory: "Quần Nam", 
    price: 490000, 
    oldPrice: 600000, 
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800", 
    tag: "Bán chạy", 
    code: "MJE-013",
    sizes: ["29", "30", "31", "32"],
    description: "Chất liệu jean co giãn tốt giúp thoải mái khi vận động. Form Slim-fit ôm nhẹ đùi và ống quần, tạo cảm giác gọn gàng và tôn chiều cao."
  },
  { 
    id: 14, 
    name: "Quần Kaki túi hộp Cargo", 
    slug: "quan-kaki-tui-hop-cargo",
    category: "Quần kaki", 
    subCategory: "Quần Nam", 
    price: 350000, 
    oldPrice: 420000, 
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800", 
    tag: "Mới", 
    code: "CAR-014",
    sizes: ["M", "L", "XL"],
    description: "Vải kaki dày dặn chống mài mòn, thiết kế túi hộp hai bên hông đậm chất quân đội, mang lại vẻ ngoài bụi bặm và mạnh mẽ."
  },
  { 
    id: 15, 
    name: "Quần Tây Âu thanh lịch", 
    slug: "quan-tay-au-thanh-lich",
    category: "Quần âu", 
    subCategory: "Quần Nam", 
    price: 550000, 
    oldPrice: 680000, 
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800", 
    tag: "", 
    code: "TRO-015",
    sizes: ["29", "30", "31", "32"],
    description: "Vải nhập khẩu chống nhăn tuyệt đối, đường ly quần được ép nhiệt sắc sảo, giúp quý ông luôn tự tin trong các cuộc họp quan trọng."
  },

  // --- NHÓM: THỂ THAO ---
  { 
    id: 16, 
    name: "Bộ đồ thể thao nam", 
    slug: "bo-do-the-thao-nam",
    category: "Bộ đồ thể thao", 
    subCategory: "Thể Thao", 
    price: 650000, 
    oldPrice: 800000, 
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800", 
    tag: "Sale", 
    code: "SET-016",
    sizes: ["M", "L", "XL"],
    description: "Sử dụng công nghệ Dri-fit thấm hút cực nhanh, giúp cơ thể luôn khô thoáng. Thiết kế co giãn đa chiều hỗ trợ tối đa khi tập luyện cường độ cao."
  },
  { 
    id: 17, 
    name: "Áo tập gym nữ chuyên dụng", 
    slug: "ao-tap-gym-nu",
    category: "Áo thể thao", 
    subCategory: "Thể Thao", 
    price: 220000, 
    oldPrice: 280000, 
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800", 
    tag: "Mới", 
    code: "SGY-017",
    sizes: ["S", "M", "L"],
    description: "Chất liệu thun lạnh siêu nhẹ, thiết kế ôm sát hỗ trợ cơ bắp và giảm ma sát khi thực hiện các bài tập yoga hoặc gym."
  },

  // --- PHỤ KIỆN ---
  { 
    id: 18, 
    name: "Thắt lưng da nam", 
    slug: "that-lung-da-nam",
    category: "Thắt lưng", 
    subCategory: "Phụ Kiện", 
    price: 290000, 
    oldPrice: 350000, 
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800", 
    tag: "Mới", 
    code: "BEL-018",
    sizes: ["Freesize"],
    description: "Da thật 100%, mặt khóa hợp kim chống gỉ. Thiết kế tối giản tinh tế, dễ dàng điều chỉnh độ dài theo vòng bụng."
  },
  { 
    id: 19, 
    name: "Túi xách nữ sang trọng", 
    slug: "tui-xach-nu-sang-trong",
    category: "Túi xách", 
    subCategory: "Phụ Kiện", 
    price: 1250000, 
    oldPrice: 1500000, 
    image: "https://images.unsplash.com/photo-1584917033904-493bb3c3cc08?w=800", 
    tag: "Bán chạy", 
    code: "BAG-019",
    sizes: ["Freesize"],
    description: "Phụ kiện không thể thiếu của phái đẹp. Da mềm mịn, ngăn chứa thông minh có thể đựng vừa điện thoại, ví tiền và mỹ phẩm cơ bản."
  },
  { 
    id: 20, 
    name: "Mũ lưỡi trai phối lưới", 
    slug: "mu-luoi-trai-phoi-luoi",
    category: "Mũ thể thao", 
    subCategory: "Phụ Kiện", 
    price: 150000, 
    oldPrice: 190000, 
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800", 
    tag: "Sale", 
    code: "HAT-020",
    sizes: ["Freesize"],
    description: "Phần sau phối lưới thoáng khí, điều chỉnh kích cỡ bằng quai cài tiện lợi. Kiểu dáng trẻ trung, phù hợp cho cả nam và nữ khi tham gia hoạt động ngoài trời."
  }
];